const Mock = [
    {id: "1",
    nombre: "Cono doble", 
    descripcion: "Cono de 2 bochas",
    precio: 200, 
    stock: 10,
    foto: "https://apilibereco.ultimasoluciones.com/uploads/presentacion26_sabor.png",
    descripcion2:"Cono de 2 bochas a elección, de toda nuestra variedad de exquisitos sabores", 
},
{id: "2",
    nombre: "Cono triple", 
    descripcion: "Cono de 3 bochas",
    precio: 250, 
    stock: 10,
    foto: "https://apilibereco.ultimasoluciones.com/uploads/presentacion27_sabor.png",
    descripcion2:"Cono de 3 bochas a elección, de toda nuestra variedad de exquisitos sabores", 
},
{id: "3",
    nombre: "Canastita", 
    descripcion: "Canastita de 2 bochas",
    precio: 300, 
    stock: 10,
    foto: "https://static.wixstatic.com/media/d2e20e_6fde023aee624f998807e15d5bfaa539~mv2.png/v1/crop/x_8,y_26,w_407,h_430/fill/w_352,h_384,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/d2e20e_6fde023aee624f998807e15d5bfaa539~mv2.png",
    descripcion2:"Canasta de 3 bochas a elección, de toda nuestra variedad de exquisitos sabores", 
},
{id: "4",
    nombre: "Cuarto de helado", 
    descripcion: "1/4kg de helado",
    precio: 400, 
    stock: 10,
    foto: "https://images.rappi.com.ar/products/405978-1585756814189.png",
    descripcion2:"1/4kg de helado a elección, de toda nuestra variedad de exquisitos sabores", 
},
{id: "5",
    nombre: "Kilo de helado", 
    descripcion: "1kg de helado",
    precio: 1000, 
    stock: 10,
    foto: "https://images.rappi.com.ar/products/405978-1585756814189.png",
    descripcion2:"1kg de helado a elección, de toda nuestra variedad de exquisitos sabores", 
}
]

export default Mock;