// const Mock = [
//     {id: "1",
//     nombre: "Cono doble", 
//     descripcion: "Cono de 2 bochas",
//     precio: 200, 
//     stock: 10,
//     foto: "https://apilibereco.ultimasoluciones.com/uploads/presentacion26_sabor.png",
//     descripcion2:"Cono de 2 bochas a elección, de toda nuestra variedad de exquisitos sabores",
//     categoria: "obleas", 
// },
// {id: "2",
//     nombre: "Cono triple", 
//     descripcion: "Cono de 3 bochas",
//     precio: 250, 
//     stock: 10,
//     foto: "https://apilibereco.ultimasoluciones.com/uploads/presentacion27_sabor.png",
//     descripcion2:"Cono de 3 bochas a elección, de toda nuestra variedad de exquisitos sabores", 
//     categoria: "obleas",
// },
// {id: "3",
//     nombre: "Cuarto de helado", 
//     descripcion: "1/4kg de helado",
//     precio: 400, 
//     stock: 10,
//     foto: "https://images.rappi.com.ar/products/405978-1585756814189.png",
//     descripcion2:"1/4kg de helado a elección, de toda nuestra variedad de exquisitos sabores", 
//     categoria: "vasos",
// },
// {id: "4",
//     nombre: "Kilo de helado", 
//     descripcion: "1kg de helado",
//     precio: 1000, 
//     stock: 10,
//     foto: "https://images.rappi.com.ar/products/405978-1585756814189.png",
//     descripcion2:"1kg de helado a elección, de toda nuestra variedad de exquisitos sabores", 
//     categoria: "vasos",
// }
// ]

// export default Mock;